[dev]
tauri = { cmd = "cargo tauri dev", working_dir = "crates/backend" }
[build]
tauri = { cmd = "cargo tauri build", working_dir = "crates/backend" }
[setup]
node = { cmd = [
    { cmd = "rustup target add wasm32-unknown-unknown", working_dir = "crates/frontend" },
    { cmd = "cargo install trunk wasm-bindgen-cli", working_dir = "crates/frontend" },
] }
