name: "Build And Release"
on:
  push:
    branches: ["release"]
  pull_request:
    branches: ["release"]

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: recursive

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: Install tauri cli
        run: cargo install tauri-cli

      - name: Install app dependencies and build it
        run: cd crates/frontend && yarn && cd .. && cd ..

      - name: Build the app
        run: cd crates/backend && cargo tauri build

      - name: Release
        uses: softprops/action-gh-release@v1
        if: matrix.platform == 'ubuntu-latest'
        with:
          files: |
            target/release/bundle/appimage/*.AppImage
            target/release/bundle/deb/*.deb
            LICENSE
        if: matrix.platform == 'macos-latest'
        with:
          files: |
            target/release/bundle/dmg/*.dmg
            target/release/bundle/macos/*.app
            LICENSE
